// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNS2jX2opO5MdDP3bIit9a0typMJixVyc',
    appId: '1:745048393213:web:731a86521fbad5fe86c594',
    messagingSenderId: '745048393213',
    projectId: 'cutshot-35dae',
    authDomain: 'cutshot-35dae.firebaseapp.com',
    storageBucket: 'cutshot-35dae.appspot.com',
    measurementId: 'G-JVP4GDEJ4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL9whmtwYUcg6o9191YtsSZn9qDHZ93oc',
    appId: '1:745048393213:android:3e25ba27b2b5cde586c594',
    messagingSenderId: '745048393213',
    projectId: 'cutshot-35dae',
    storageBucket: 'cutshot-35dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLrHAgMxJ2r6GxX1Bvg4NP12vdO4lnQK4',
    appId: '1:745048393213:ios:f425ca3b3a1a862786c594',
    messagingSenderId: '745048393213',
    projectId: 'cutshot-35dae',
    storageBucket: 'cutshot-35dae.appspot.com',
    iosClientId: '745048393213-hols64dk8v4gsm2ubfs1u6nhhcub9ac3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cutshot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLrHAgMxJ2r6GxX1Bvg4NP12vdO4lnQK4',
    appId: '1:745048393213:ios:f425ca3b3a1a862786c594',
    messagingSenderId: '745048393213',
    projectId: 'cutshot-35dae',
    storageBucket: 'cutshot-35dae.appspot.com',
    iosClientId: '745048393213-hols64dk8v4gsm2ubfs1u6nhhcub9ac3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cutshot',
  );
}
